github_actions:
  - changed-files:
    - any-glob-to-any-file: ".github/**/*.yml"

documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - "**/*.md"
      - "docs/**/*"
      - "website/**/*"

dependencies:
  - changed-files:
    - any-glob-to-any-file: 
      - "**/Cargo.toml"
      - "**/Cargo.lock"

rust:
  - changed-files:
    - any-glob-to-any-file: "**/*.rs"

build:
  - changed-files:
    - any-glob-to-any-file:
      - "**/build.rs"
      - "**/build.sh"
      - "**/Makefile"

tests:
  - changed-files:
    - any-glob-to-any-file:
      - "**/tests/**/*"
      - "**/*test*.rs"

uefi:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*uefi*"
      - "**/esp/**/*"
