github_actions:
  - changed-files:
    - any-glob-to-any-file: ".github/**/*.yml"
documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - "**/*.md"
      - "docs/**/*"
      - "website/**/*"
dependencies:
  - changed-files:
    - any-glob-to-any-file: "**/go.mod"
