[package]
name = "citros"
version = "0.2.1"
edition = "2024"

[[bin]]
name = "citros"
path = "src/main.rs"

[dependencies]
# no_std環境なので、標準ライブラリは使用しない

[profile.release]
panic = "abort"
lto = true
opt-level = 3